version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/"
      - "nodejs/eks"
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: "provider"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
