linters:
  enable:
  - errcheck
  - goconst
  - gofmt
  - gosec
  - gosimple
  - govet
  - ineffassign
  - lll
  - megacheck
  - misspell
  - nakedret
  - revive
  - staticcheck
  - unused
  - unconvert
  enable-all: false
run:
  timeout: 10m
