// *** WARNING: this file was generated by pulumi-gen-eks. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Eks
{
    /// <summary>
    /// ClusterCreationRoleProvider is a component that wraps creating a role provider that can be passed to the `Cluster`'s `creationRoleProvider`. This can be used to provide a specific role to use for the creation of the EKS cluster different from the role being used to run the Pulumi deployment.
    /// </summary>
    [EksResourceType("eks:index:ClusterCreationRoleProvider")]
    public partial class ClusterCreationRoleProvider : global::Pulumi.ComponentResource
    {
        [Output("role")]
        public Pulumi.Aws.Iam.Role Role { get; private set; }


        /// <summary>
        /// Create a ClusterCreationRoleProvider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ClusterCreationRoleProvider(string name, ClusterCreationRoleProviderArgs? args = null, ComponentResourceOptions? options = null)
            : base("eks:index:ClusterCreationRoleProvider", name, args ?? new ClusterCreationRoleProviderArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ClusterCreationRoleProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("profile")]
        public Input<string>? Profile { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        public ClusterCreationRoleProviderArgs()
        {
        }
        public static new ClusterCreationRoleProviderArgs Empty => new ClusterCreationRoleProviderArgs();
    }
}
