// *** WARNING: this file was generated by pulumi-gen-eks. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Eks.Inputs
{

    /// <summary>
    /// Describes a mapping from an AWS IAM user to a Kubernetes user and groups.
    /// </summary>
    public sealed class UserMappingArgs : Pulumi.ResourceArgs
    {
        [Input("groups", required: true)]
        private InputList<string>? _groups;

        /// <summary>
        /// A list of groups within Kubernetes to which the user is mapped to.
        /// </summary>
        public InputList<string> Groups
        {
            get => _groups ?? (_groups = new InputList<string>());
            set => _groups = value;
        }

        /// <summary>
        /// The ARN of the IAM user to add.
        /// </summary>
        [Input("userArn", required: true)]
        public Input<string> UserArn { get; set; } = null!;

        /// <summary>
        /// The user name within Kubernetes to map to the IAM user. By default, the user name is the ARN of the IAM user.
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public UserMappingArgs()
        {
        }
    }
}
