// *** WARNING: this file was generated by pulumi-gen-eks. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Eks.Outputs
{

    /// <summary>
    /// MIME document parts for nodeadm configuration. This can be shell scripts, nodeadm configuration or any other user data compatible script.
    /// 
    /// See for more details: https://awslabs.github.io/amazon-eks-ami/nodeadm/.
    /// </summary>
    [OutputType]
    public sealed class NodeadmOptions
    {
        /// <summary>
        /// The ARN of the access policy to associate with the principal
        /// </summary>
        public readonly string Content;
        /// <summary>
        /// The MIME type of the content. Examples are `text/x-shellscript; charset="us-ascii"` for shell scripts, and `application/node.eks.aws` nodeadm configuration.
        /// </summary>
        public readonly string ContentType;

        [OutputConstructor]
        private NodeadmOptions(
            string content,

            string contentType)
        {
            Content = content;
            ContentType = contentType;
        }
    }
}
