// *** WARNING: this file was generated by pulumi-gen-eks. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Eks.Inputs
{

    /// <summary>
    /// Configuration for the compute capability of your EKS Auto Mode cluster.
    /// </summary>
    public sealed class ClusterComputeConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("nodePools")]
        private InputList<string>? _nodePools;

        /// <summary>
        /// Configuration for node pools that defines the compute resources for your EKS Auto Mode cluster. Valid options are `general-purpose` and `system`.
        /// 
        /// By default, the built-in `system` and `general-purpose` nodepools are enabled.
        /// </summary>
        public InputList<string> NodePools
        {
            get => _nodePools ?? (_nodePools = new InputList<string>());
            set => _nodePools = value;
        }

        /// <summary>
        /// The ARN of the IAM Role EKS will assign to EC2 Managed Instances in your EKS Auto Mode cluster. This value cannot be changed after the compute capability of EKS Auto Mode is enabled.
        /// </summary>
        [Input("nodeRoleArn")]
        public Input<string>? NodeRoleArn { get; set; }

        public ClusterComputeConfigArgs()
        {
        }
        public static new ClusterComputeConfigArgs Empty => new ClusterComputeConfigArgs();
    }
}
