name: "Prerequisites"

on:
  workflow_call:
    inputs:
      is_pr:
        type: boolean
        required: true
      is_automated:
        type: boolean
        required: true
      default_branch:
        type: string
        required: true
    outputs:
      version:
        description: "Provider version being built"
        value: ${{ jobs.prerequisites.outputs.version }}

env:
  ALT_AWS_ACCESS_KEY_ID: ${{ secrets.ALT_AWS_ACCESS_KEY_ID }}
  ALT_AWS_SECRET_ACCESS_KEY: ${{ secrets.ALT_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-west-2
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
  GOLANGCI_LINT_VERSION: v1.61.0
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
  PROVIDER: eks
  PUBLISH_REPO_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  PUBLISH_REPO_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_API: https://api.pulumi-staging.io
  PULUMI_ENABLE_RESOURCE_REFERENCES: "1"
  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
  PYPI_USERNAME: __token__
  SIGNING_KEY: ${{ secrets.JAVA_SIGNING_KEY }}
  SIGNING_KEY_ID: ${{ secrets.JAVA_SIGNING_KEY_ID }}
  SIGNING_PASSWORD: ${{ secrets.JAVA_SIGNING_PASSWORD }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  TF_APPEND_USER_AGENT: pulumi

jobs:
  prerequisites:
    name: prerequisites
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.provider-version.outputs.version }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: pulumi/provider-version-action@v1
      id: provider-version
      with:
        set-env: 'PROVIDER_VERSION'
    - name: Cache examples generation
      uses: actions/cache@v4
      with:
        path: |
          .pulumi/examples-cache
        key: ${{ runner.os }}-${{ hashFiles('provider/go.sum') }}
    - name: Setup tools
      uses: ./.github/actions/setup-tools
      with:
        tools: go, pulumictl, pulumicli, schema-tools
    - name: Install plugins
      run: make install_plugins
    - name: Generate schema
      run: make schema
    - name: Build provider binary
      run: make provider
    - name: Unit-test provider code
      run: make test_provider
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - if: inputs.is_pr
      name: Check Schema is Valid
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        {
          echo "SCHEMA_CHANGES<<$EOF";
          schema-tools compare -r github://api.github.com/pulumi -p eks -o "${{ inputs.default_branch }}" -n --local-path=provider/cmd/pulumi-resource-eks/schema.json;
          echo "$EOF";
        } >> "$GITHUB_ENV"
    - if: inputs.is_pr && inputs.is_automated == false
      name: Comment on PR with Details of Schema Check
      uses: thollander/actions-comment-pull-request@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        comment_tag: schemaCheck
        message: >+
          ${{ env.SCHEMA_CHANGES }}


          Maintainer note: consult the [runbook](https://github.com/pulumi/platform-providers-team/blob/main/playbooks/tf-provider-updating.md) for dealing with any breaking changes.

    - name: Upload bin
      uses: ./.github/actions/upload-bin

    - name: Upload schema-embed.json
      uses: actions/upload-artifact@v4
      with:
        name: schema-embed.json
        path: provider/cmd/pulumi-resource-eks/schema-embed.json
        retention-days: 30
