name: pull-request
"on":
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: |
            PR is now waiting for a maintainer to run the acceptance tests. This PR will only perform build and linting.
            **Note for the maintainer:** To run the acceptance tests, please comment */run-acceptance-tests* on the PR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@d62853bc9e466834c74cefb34fad78535582e21a
        with:
          repo: pulumi/pulumictl
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.nodeversion}}
          registry-url: https://registry.npmjs.org
      - name: Install Yarn
        run: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
      - name: Update PATH for Yarn
        run: |
          echo "::add-path::$HOME/.yarn/bin"
          echo "::add-path::$HOME/.config/yarn/global/node_modules/.bin"
      - name: Run lint
        run: make lint
